### PR TITLE
Upgrade to DB 2.0 API, using file ids instead of file names, to allow end users to move files around

### PR DESCRIPTION
**Pull request by mful**
Forked @wooly 's 2.0 branch, and added support for file ids.

### CODE REVIEW

**Comment by wooly** [comment]
This is great! I was just bodging it together for a prototype I had to build.

**Review by depresto — APPROVED** [review]

**Comment by mful** [comment]
@depresto thanks for taking a look at this. I can probably take a look at the CI failures this weekend — looks like something to do with not stubbing requests, or something with the testing access token. Is that what's blocking a merge here?

**Comment by edlvj** [comment]
Any update on this?
I would like to see this merged in. 1+

**Comment by robin850** [comment]
Hey there !

I'm really sorry for the late answer, I haven't been able to find the time and motivation to work on this project recently ! Parts of this pull request have been cherry-picked in #31 and 2.0.0.rc1 is available on RubyGems with these changes if you want to use Dropbox API v2 in your application. If there's no bug with this new version, a final release will be available in two weeks or so.

Thank you so much for your patch and your patience ! You've been properly credited in the Git history and in the changelog file. ❤️ 💙 💛 💚 💜

**Pull request closed without merging**
